name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  job_lint_and_test:
    name: Lint, Test and Build
    uses: ./.github/workflows/lint-and-test.yml

  job_upload_coverage:
    name: Upload Coverage to Codecov

    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'branch' }}
    needs: job_lint_and_test

    steps:
      - name: Checkout, Setup Node.js v20.x and Install dependencies
        uses: manferlo81/action-checkout-node-install@v0
        with:
          node-version: 20.x

      - name: Run tests
        run: npm test
        env:
          CI: true

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/coverage-final.json

  job_create_release:
    name: Create GitHub Release

    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' }}
    needs: job_lint_and_test

    permissions:
      contents: write

    steps:
      - name: Checkout, Setup Node.js v20.x and Install dependencies
        uses: manferlo81/action-checkout-node-install@v0
        with:
          node-version: 20.x

      - name: Build
        run: npm run build

      - name: Create tarball
        run: npm pack

      - name: Create Release
        uses: manferlo81/action-auto-release@v0
        with:
          files: selective-option-*.tgz

  job_publish_to_npm:
    name: Publish to npm registry

    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' }}
    needs: job_lint_and_test

    steps:
      - name: Checkout, Setup Node.js v20.x and Install dependencies
        uses: manferlo81/action-checkout-node-install@v0
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/

      - name: Build
        run: npm run build

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  job_publish_to_gpr:
    name: Publish to GitHub Packages

    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' }}
    needs: job_lint_and_test

    permissions:
      packages: write

    steps:
      - name: Checkout, Setup Node.js v20.x and Install dependencies
        uses: manferlo81/action-checkout-node-install@v0
        with:
          node-version: 20.x
          registry-url: https://npm.pkg.github.com/

      - name: Build
        run: npm run build

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
